[build]
  base    = "."
  publish = "dist"
  command = "npm run netlify-build"
  environment = {NODE_VERSION = "16.16.0" }

# Set enviroment variable prompts for templates
[template.environment]
  DAILY_API_KEY = "Your Daily API key"

[[redirects]]
  # Proxies POST request to Daily /rooms endpoint 
  # The placeholder below gets replaced when the build command runs
  # as suggested here: https://docs.netlify.com/configure-builds/file-based-configuration/#inject-environment-variable-values
  from = "/api/rooms"
  to = "https://api.daily.co/v1/rooms"
  force = true
  # If you run the application locally via `npm run dev`, the following will be replaced
  # with the API key from your .env file. 
  # DO NOT COMMIT THIS CHANGE.
  headers = { Authorization = "Bearer DAILY_API_KEY_PLACEHOLDER" }